languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Burro"
# logo = "svg/logo.svg"
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[params.author]
  name = "Marco Burro"
  image = "img/me.jpeg"
  headline = "Some day I'll post stuff here"
  links = [
    { github = "https://github.com/buurro" },
    { twitter = "https://twitter.com/BurroMarco" },
    { bluesky = "https://bsky.app/profile/marco.ooo" },
  ]
