# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "congo"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = false

# mainSections = ["section1", "section2"]
# robots = ""

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = false
  showTaxonomies = false
  showWordCount = false
  # sharingLinks = ["facebook", "twitter", "pinterest", "reddit", "linkedin", "email"]

[list]
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  groupByYear = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[umamiAnalytics]
  site = "6b55cd82-d3ad-4001-8536-c873b4af5364"
  domain = "umami.app.marco.ooo"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""

[footer]
  showAppearanceSwitcher = false
  showScrollToTop = true
